apiVersion: v1
kind: Secret
metadata:
  name: dagster-postgresql-secret
type: Opaque
stringData:
  POSTGRESQL_HOSTNAME: postgres
  POSTGRESQL_USERNAME: dagster
  POSTGRESQL_PASSWORD: dagster
  POSTGRESQL_DB: dagster
